### ISSUE TITLE
Does it only support one bin?

### ISSUE THREAD

**Issue by sameerkumar18** [jerry800416/3D-bin-packing#1]
Hi @jerry800416 !
First of all, thanks a lot for your work on this - You've really done tremendous progress compared to the original repo!
I had a question - You've mentioned [here](https://github.com/jerry800416/3D-bin-packing/blob/master/README.md#:~:text=Add%20bin%20and%20items%20to%20packer%20%3A%20(Warning%20%3A%20You%20can%20only%20add%20one%20bin%2Cbut%20you%20can%20add%20many%20items.)) _**"Warning : You can only add one bin,but you can add many items."**_ - Can you please help me understand whether the package supports multiple bins and the distribution of items among those available bins? Or does it support the distribution of items only with a single bin? (Also I'm assuming Bin = Box)
TIA!

**Comment by jerry800416** [comment]
This repo only supports single bin , but I will consider fix this issue if I have time.

**Comment by jerry800416** [comment]
@sameerkumar18 Multiple Bins are now supported, please refer to the Readme.

**Comment by jerry800416** [comment]
This issue has been resolved, please reopen if you have other questions.
