### ISSUE TITLE
is it possible to fix the distribute_items=True

### ISSUE THREAD

**Issue by Westlife1002** [jerry800416/3D-bin-packing#10]
when I set the parameter to distribute_items=True, it reported error at :   
```
File "C:\Users\usr\Desktop\3DBP\py3dbp\main.py", line 513, in pack
    self.items.remove(item)
ValueError: list.remove(x): x not in list
```

is this issue easy to fix?

**Comment by moschd** [comment]
Hi @Westlife1002,
Can you share the input that you used to get this error?

**Comment by Westlife1002** [comment]
is this repo supports multiple bin and item distribution now?

**Comment by jerry800416** [comment]
> is this repo supports multiple bin and item distribution now?

I fixed this issue in the latest version, please refer to the Readme.

**Comment by jerry800416** [comment]
This issue has been resolved, please reopen if you have other questions.
