### ISSUE TITLE
There is no implementation of writing the part number on the item in example 6

### ISSUE THREAD

**Issue by mr-135** [jerry800416/3D-bin-packing#16]

**Comment by jerry800416** [comment]
please read README about How to use.
you must set write_num=True
```Python
for b in packer :
    painter = Painter(b)
    fig = painter.plotBoxAndItems(
        title=b.partno,
        alpha=0.2,         # set item alpha
        write_num=True,    # open/close write part number 
        fontsize=10        # control write_num fontsize
    )
fig.show() 
```
It is also recommended to set alpha to 0.2

**Comment by mr-135** [comment]
The problem has been solved, thank you very much!













At 2023-06-29 15:03:25, "Shiu Ruei-Chang" ***@***.***> wrote:

please read README about How to use.
you must set write_num=True
for b in packer : painter = Painter(b) fig = painter.plotBoxAndItems( title=b.partno, alpha=0.2, # set item alpha write_num=True, # open/close write part number fontsize=10 # control write_num fontsize ) fig.show()

**Comment by jerry800416** [comment]
This issue has been resolved, please reopen if you have other questions.
