### ISSUE TITLE
Pivot point refers to which point？

### ISSUE THREAD

**Issue by mr-135** [jerry800416/3D-bin-packing#17]

**Comment by jerry800416** [comment]
I'm sorry I need more info, can you describe it a bit more?

**Comment by mr-135** [comment]
I'm sorry I just read it today that the back lower left corner of the item will be placed at the pivot. So the coordinates of the pivot point are the lower-left coordinates of the item. So the question I asked yesterday has been solved, thank you for your reply.

**Comment by jerry800416** [comment]
This issue has been resolved, please reopen if you have other questions.
