### ISSUE TITLE
Floating boxes with Fixpoint = True

### ISSUE THREAD

**Issue by fafa95** [jerry800416/3D-bin-packing#4]
Gravity feature is not working very well.

After placing the first layer of boxes on the floor, boxes going on top of the previous ones are not really taking support surface into consideration. In the gif, check for the placement of items "item 8", "item32" or "item 9"... this is quite a extreme case as there are 33 items placed and all are different.

![48](https://user-images.githubusercontent.com/26931070/148433080-0dff99da-a040-4921-9f18-158aeb666619.gif)

This issue I think is related with Bin.checkDepth() function not working as it should:

```
if self.fix_point == True:
    [w,h,d] = dimension
    [x,y,z] = [float(pivot[0]),float(pivot[1]),float(pivot[2])]

    for i in range(3):
        # fix height
        y = self.checkHeight([x,x+float(w),y,y+float(h),z,z+float(d)])
        # fix width
        x = self.checkWidth([x,x+float(w),y,y+float(h),z,z+float(d)])
        # fix depth
        z = self.checkDepth([x,x+float(w),y,y+float(h),z,z+float(d)])

    self.fit_items = np.append(self.fit_items,np.array([[x,x+float(w),y,y+float(h),z,z+float(d)]]),axis=0)
    item.position = [set2Decimal(x),set2Decimal(y),set2Decimal(z)]
```

```
def checkDepth(self,unfix_point):
    ''' fix item position z '''
    z_ = [[0,0],[float(self.depth),float(self.depth)]]
    for j in self.fit_items:
        # creat x set
        x_bottom = set([i for i in range(int(j[0]),int(j[1]))])
        x_top = set([i for i in range(int(unfix_point[0]),int(unfix_point[1]))])
        # creat y set
        y_bottom = set([i for i in range(int(j[2]),int(j[3]))])
        y_top = set([i for i in range(int(unfix_point[2]),int(unfix_point[3]))])
        # find intersection on x set and y set.
        if len(x_bottom & x_top) != 0 and len(y_bottom & y_top) != 0 :
            z_.append([float(j[4]),float(j[5])])
    top_depth = unfix_point[5] - unfix_point[4]
    # find diff set on z_.
    z_ = sorted(z_, key = lambda z_ : z_[1])
    for j in range(len(z_)-1):
        if z_[j+1][0] -z_[j][1] >= top_depth:
            return z_[j][1]
    return unfix_point[4]
```

I tried to understand how checkHeight, checkWidth and specially for this case, checkDepth functions work, but I didn't succeed due to the compact coding.

It would be nice to create a new property which defines the minimum % of surface that has to be supported from below.
For example, a box w,h,d=8,5,10 and rotation=0, would have a surface of 40 u^2.
If we define a support_surface_ratio=0.75, then at least 30 u^2 of surface must be supported from below by other boxes to consider that position a valid placement.

Another option that could be implemented in parallel, would be to check if at least 3 out of the 4 vertices of the supporting face of a box are under support. If yes, then it can be placed in that position even if the surface under support is below the ratio.

I would really appreciate if you could find a solution for this, or if you don't have the time, to give me some insights about how a position is fixed using the functions above.

Thanks!

**Comment by lucabonno** [comment]
Hey,

thanks for the great library!
I have the same issue is reporting @fafa95; see below, especially for the green box.

![2022-01-17_08h55_48](https://user-images.githubusercontent.com/70065540/149730322-96acf92c-3d7e-4624-8e6f-ceac362effa8.png)
![2022-01-17_08h59_28](https://user-images.githubusercontent.com/70065540/149730344-2a8e36e0-c15e-4b14-8a50-f18242ee9768.png)

**Comment by lucabonno** [comment]
Hey,

thanks for the great library! I've the same issue for the example below (especially the green box).
![2022-01-17_08h55_48](https://user-images.githubusercontent.com/70065540/149731792-1d7ea7c4-ee0d-4ac8-942d-76302700eea1.png)
![2022-01-17_09h09_34](https://user-images.githubusercontent.com/70065540/149731799-aae1ffb3-6afe-4c57-97bd-4c37f7aaa78f.png)

I'm trying to follow the checkHeight/Width/depth methods for understanding logics behind (so far, I weren't able to find a solution).
Appreciate a help.

Luca

**Comment by jerry800416** [comment]
This repo currently does not take into account the support surface, the gravity function refers to the calculation of the gravity distribution of the box.

checkHeight, checkWidth and check Depth refer to fix the float problem in original repo.

@fafa95 :Thank you for the support surface solution, but I don't have time to solve this problem in the near future, I would be very happy if you would like to contribute code.

**Comment by jerry800416** [comment]
@fafa95 @lucabonno The problem with the support surface has been fixed, I added two rules to check the stability of the item.
1. Define a support ratio(default is 0.75), if the ratio below the support surface does not exceed this ratio, compare the next rule.
2. If there is no support under any of the bottom four vertices of the item, then remove the item.

For details, please refer to the Readme. 
If you have other better rules, please raise an issue.

**Comment by jerry800416** [comment]
This issue has been resolved, please reopen if you have other questions.
